var res = {
    loading_png : "res/loading.png",
    titleHome_png : "res/titleHome.png",
    btnExitHome_png : "res/btnExitHome.png",
    btnPlay_png : "res/btnPlay.png",
    btnOnMusic_png : "res/btnOnMusic.png",
    btnOnSound_png : "res/btnOnSound.png",
    btnOffMusic_png : "res/btnOffMusic.png",
    btnOffSound_png : "res/btnOffSound.png",
    BGHome_audio : "res/Audio_BGHome.mp3",
    PopUpExit_png : "res/bgExit.png",
    btnOKExit_png : "res/btnOkExit.png",
    btnCancelExit_png : "res/btnCancelExit.png",
    BGMenuLevel_png : "res/bgMenuLevel.png",
    btnLevel_png : "res/btnLevel.png",
    imgStartLock_png : "res/imgStarLock.png",
    imgStarLevel_png : "res/imgStarLevel.png",
    imgLock_png : "res/imgLock.png",
    btnExitLevel_png : "res/btnExitLevel.png",
    PopUpPause_png : "res/playDialogPause.png",
    btnPlayGame_png : "res/playBtnPlay.png",
    btnRestart_png : "res/playBtnRestart.png",
    btnBackMenu_png : "res/playBtnBackMenu.png",
    PopUpTarget_png : "res/playDialogTarget.png",
    btnOK_png : "res/playBtnOk.png",
    btnBack_png : "res/playBtnBack.png",
    playBackGround_png : "res/playBackgound.png",
    playMouseLife_png : "res/playInfLife.png",
    playLevel_png : "res/playInfLevel.png",
    playScore_png : "res/playInfScore.png",
    playInfor_png : "res/playInformation.png",
    playBtnPause_png : "res/playBtnPause.png",
    BGPlay_auido : "res/Audio_BGPlay.mp3",
    playLandUp_png : "res/playLandUp.png",
    playLandDown_png : "res/playLandDown.png",
    mouseAnimation_png : "res/MouseAnimation.png",
    mouseAnimation_plist : "res/MouseAnimation.plist",
    oldAnimation_png : "res/OldAnimation.png",
    oldAnimation_plist : "res/OldAnimation.plist",
    playBoom_png : "res/playBoom.png",
    playDiamond_png : "res/playDiamond.png",
    Audio_MousePeek : "res/Audio_MousePeek.mp3",
    Audio_HitMouse_mp3 : "res/Audio_HitMouse.mp3",
    Audio_Boom_wav : "res/Audio_Boom.wav",
    Audio_Old_mp3 : "res/Audio_old.mp3",
    Audio_Diamond_mp3 : "res/Audio_Diamond.mp3",
    star_png : "res/stars.png",
    playCheck_png : "res/playCheck.png",
    btnNextLevel_png : "res/playBtnNext.png",
    popUpWin_png : "res/playDialogWin.png",
    popUpLose_png : "res/playDialogLose.png",
    BgHome_png : "res/bgHome.png",
    scrollBarBlack_png : "res/scrollbarBackground.png",
    scrollBarColor_png : "res/scrollbarColor1.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
